version: '3.8'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./database_devices.sql:/docker-entrypoint-initdb.d/init.sql